FROM python:3-slim
RUN pip install --upgrade pip && pip install pika pandas db-dtypes psycopg2-binary google-cloud-bigquery google-auth google-auth-httplib2 google-api-python-client pycountry sqlalchemy rapidfuzz
WORKDIR /srv